### PR TITLE
Demo lack of error report.

### PR DESCRIPTION
**Pull request by jgfoster**
Demo of #288

Tests are only run on a PR, so here is one to demo the test failure without an error report.

### CODE REVIEW

**Comment by ianfixes** [comment]
I had to really puzzle this one out, and I'm still not 100% on why the logs weren't getting printed.  It looks like the problem is mostly related to mismatching `after(:each)` with `before(:all)` -- I was using `:all` to avoid building the executable multiple times, and I think I have a better solution on my local branch now.

**Comment by jgfoster** [comment]
As you will see in #294, I'm very interested in avoiding duplicate compiles. I'm not sure how this ties in but I'm glad you are working on it!

**Comment by ianfixes** [comment]
I'm curious if this fixes the issue for you locally https://github.com/Arduino-CI/arduino_ci/pull/296/commits/22e514d9aade4aa8226bca0687a67b330d42f020

**Comment by jgfoster** [comment]
In my local macOS environment, this is what I get now:

```
Unit testing foo.cpp with g++ for uno... 

Last command:  $ g++ -std=c++0x -o /Users/jfoster/Documents/Arduino/arduino_ci/SampleProjects/TestSomething/unittest_foo.cpp.bin -DARDUINO=100 -g -O1 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -D__AVR__ -D__AVR_ATmega328P__ -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -I/Users/jfoster/Documents/Arduino/arduino_ci/cpp/arduino -I/Users/jfoster/Documents/Arduino/arduino_ci/cpp/unittest -I/Users/jfoster/Documents/Arduino/libraries/TestSomething/src /Users/jfoster/Documents/Arduino/arduino_ci/cpp/arduino/Arduino.cpp /Users/jfoster/Documents/Arduino/arduino_ci/cpp/arduino/Godmode.cpp /Users/jfoster/Documents/Arduino/arduino_ci/cpp/arduino/stdlib.cpp /Users/jfoster/Documents/Arduino/arduino_ci/cpp/unittest/ArduinoUnitTests.cpp /Users/jfoster/Documents/Arduino/libraries/TestSomething/src/test-something.cpp /Users/jfoster/Documents/Arduino/libraries/TestSomething/test/foo.cpp

/Users/jfoster/Documents/Arduino/libraries/TestSomething/test/foo.cpp:6:3: error: use of undeclared identifier 'foo'; did you mean 'for'?
  foo;
  ^~~
  for
/Users/jfoster/Documents/Arduino/libraries/TestSomething/test/foo.cpp:6:6: error: expected '(' after 'for'
  foo;
     ^
2 errors generated.
```

So that is a useful error report.

**Comment by jgfoster** [comment]
And on a PR, see line 697 of https://github.com/Arduino-CI/arduino_ci/runs/2267056294.

**Comment by jgfoster** [comment]
Demo of failing PR no longer needed so being closed.

**Pull request closed without merging**
