### PR TITLE
Add test for #192: fatal error: 'Adafruit_SPIDevice.h' file not found

### PR DESCRIPTION
**Pull request by jgfoster**
This should make it easier to debug #192.

### CODE REVIEW

**Comment by ianfixes** [comment]
The motivation behind this PR seems to be illustrating the problem fixed by #213 but this doesn't quite close the loop... this project doesn't get included in the CI config.

I'm wondering if https://github.com/Arduino-CI/arduino_ci/tree/master/SampleProjects/DependOnSomething could be adapted to perform this test.

**Comment by jgfoster** [comment]
This is illustrating the problem reported in #192 (not #193) which is not yet fixed. It wasn't added to CI because it would cause the CI to fail. Once #192 is fixed then we can include it into the CI.

**Comment by jgfoster** [comment]
Replace with PR to `tdd` branch.

**Comment by ianfixes** [comment]
Rolled into #223 and merged

**Comment by ianfixes** [comment]
I got an email that

> I find that #212 still fails so this doesn't seem to be fixed.

I don't see that comment here so I assume it was retracted.  Please open a new issue if the problem comes back, as #218 will have affected quite a few things

**Comment by jgfoster** [comment]
Yes, I discovered that the problem was elsewhere.

**Pull request closed without merging**
