### PR TITLE
Use `arduino-cli` backend

### LINKED ISSUE #137: Revisit splash screen suppression on OSX
## Feature Request
Prevent splash screen on OSX

> I've found a workaround for this issue on macOS :
> 
> * Edit the plist in `/Applications/Arduino.app/Contents` and simply remove the xml tag `<splash-scren ..>`
> * to avoid that is you are in full screen the Arduino app get the main focus you must create a simple script (in Contents/MacOS) like `run-arduino.sh` that contains the following line `open -g ./Arduino`

https://github.com/arduino/Arduino/issues/1970#issuecomment-587101789

### LINKED ISSUE #155: Fix IDE auto-download in OSX Catalina (64-bit only OS)
## System: macOS

See #149 for details.

## Downloading 1.8.6 instead of most recent (currently 1.8.13)

This is a follow-up from the "bad CPU type in executable" problem reported in #149. If a copy of the IDE is not found, we download one. Unfortunately, the (hard-coded?) version obtained (1.8.6) does not work on macOS 10.16 because it is not a 64-bit application. 

## Workaround

Delete the Arduino.app in the Documents directory and install the current version in the /Applications directory.

### LINKED ISSUE #206: Implement Arduino CLI (instead of IDE) backend
## Feature Request

There are many benefits to using the Arduino CLI instead of the IDE to run commands.  But the IDE was the only way when this project was written.

Update `ArduinoCmd` (`arduino_cmd.rb`) to use the CLI instead of IDE.

This is expected to fix #137 as well as the issue of "hidden built-in" libraries like Ethernet.

This also will satisfy cross-platform, see https://github.com/Arduino-CI/arduino_ci/pull/180#issuecomment-726499615

### LINKED ISSUE #222: Properly handle libraries with spaces in names, when installed as custom libraries
If a library with a space in the name is requested, we expect it to be stored on disk as having an underscore substituted for the space.  Detection of already-installed libraries breaks somewhat in this case.  Consider the following:

```yaml
unittest:
  platforms:
    - mega2560
  libraries:
    - "Adafruit BusIO"
    # - "Adafruit_BusIO"    <= This works if you have the library pre-installed
```

### PR DESCRIPTION
**Pull request by ianfixes**
## Highlights from `CHANGELOG.md`

:tada: Arduino backend is now `arduino-cli` version `0.13.0` 🎉 

### Added
- Special handling of attempts to run the `arduino_ci.rb` CI script against the ruby library instead of an actual Arduino project
- Explicit checks for attemping to test `arduino_ci` itself as if it were a librart, resolving a minor annoyance to this developer.
- Code coverage tooling
- Explicit check and warning for library directory names that do not match our guess of what the library should/would be called

### Changed
- Arduino backend is now `arduino-cli` version `0.13.0`
- `ArduinoCmd` is now `ArduinoBackend`
- `CppLibrary` now relies largely on `ArduinoBackend` instead of making its own judgements about libraries (metadata, includes, and examples)
- `ArduinoBackend` functionality related to `CppLibrary` now lives in `CppLibrary`
- `CppLibrary` now works in an installation-first manner for exposure to `arduino-cli`'s logic -- without installation, there is no ability to reason about libraries
- `CppLibrary` forces just-in-time recursive dependency installation in order to work sensibly
- `ArduinoBackend` maintains the central "best guess" logic on what a library (on disk) might be named

### Deprecated
- `arduino_ci_remote.rb` CLI switch `--skip-compilation`
- Deprecated `arduino_ci_remote.rb` in favor of `arduino_ci.rb`

### Removed
- `ARDUINO_CI_SKIP_SPLASH_SCREEN_RSPEC_TESTS` no longer affects any tests because there are no longer splash screens since switching to `arduino-cli`

### Fixed
- Mismatches between library names in `library.properties` and the directory names, which can cause cryptic failures
- `LibraryProperties` skips over parse errors instead of crashing: only lines with non-empty keys and non-nil values are recorded

## Issues Fixed

* Fixes #137 
* Fixes #155
* Fixes #206
* Obsoletes #17 
* Obsoletes #185 
* Fixes #222
* Addresses #224

### CODE REVIEW

**Comment by ianfixes** [comment]
@per1234 one thing I'm struggling with here is how much to rely on the output of `arduino-cli lib list`.  For example, I'm noticing here is that it doesn't follow any symlinks. 

I could imagine relying on a lot of its output (which us unbelievably helpful by being json-formatted, btw), but for some of the unit tests I'd prefer to symlink dummy libraries into the Arduino libraries dir rather than fake or mock the output of `arduino-cli`.

**Comment by per1234** [comment]
> I'm noticing here is that it doesn't follow any symlinks.

Is this the same behavior you're experiencing?
```
$ ./arduino-cli version
arduino-cli Version: 0.13.0 Commit: 693a045
$ export ARDUINO_DIRECTORIES_USER=/tmp/arduino/staging
$ ./arduino-cli lib install Servo
Servo depends on Servo@1.1.7
Downloading Servo@1.1.7...
Servo@1.1.7 already downloaded
Installing Servo@1.1.7...
Installed Servo@1.1.7
$ export ARDUINO_DIRECTORIES_USER=/tmp/arduino/directories/user
$ mkdir --parents "${ARDUINO_DIRECTORIES_USER}/libraries"
$ ln -s /tmp/arduino/staging/libraries/Servo "${ARDUINO_DIRECTORIES_USER}/libraries/Servo"
$ ./arduino-cli lib list --format json
[
  {
    "library": {
      "name": "Servo",
      "author": "Michael Margolis, Arduino",
      "maintainer": "Arduino \u003cinfo@arduino.cc\u003e",
      "sentence": "Allows Arduino/Genuino boards to control a variety of servo motors.",
      "paragraph": "This library can control a great number of servos.\u003cbr /\u003eIt makes careful use of timers: the library can control 12 servos using only 1 timer.\u003cbr /\u003eOn the Arduino Due you can control up to 60 servos.\u003cbr /\u003e",
      "website": "http://www.arduino.cc/en/Reference/Servo",
      "category": "Device Control",
      "architectures": [
        "avr",
        "megaavr",
        "sam",
        "samd",
        "nrf52",
        "stm32f4",
        "mbed"
      ],
      "install_dir": "/tmp/arduino/directories/user/libraries/Servo",
      "source_dir": "/tmp/arduino/directories/user/libraries/Servo/src",
      "real_name": "Servo",
      "version": "1.1.7",
      "license": "Unspecified",
      "location": 1,
      "layout": 1,
      "examples": [
        "/tmp/arduino/directories/user/libraries/Servo/examples/Knob",
        "/tmp/arduino/directories/user/libraries/Servo/examples/Sweep"
      ],
      "provides_includes": [
        "Servo.h"
      ]
    },
    "release": {}
  }
]
```

**Comment by ianfixes** [comment]
Aah, this was my own mistake.  

Comparing `ls -l $(./arduino-cli config dump --format json | jq -r ".directories.user")/libraries` to `./arduino-cli lib list`, everything is as it should be.  I lost track of which of my dummy libraries I had actually installed.

**Comment by ianfixes** [comment]
I take that back, it's failing in a very narrow case

```console
$ ls -lo $(./arduino-cli config dump --format json | jq -r ".directories.user")/libraries | grep TestSomething
lrwxr-xr-x   1 ianfixes   78 Jan  5  2019 TestSomething -> /Users/ianfixes/Development/arduino_ci/SampleProjects/TestSomething
$ ./arduino-cli lib list | grep TestSomething
TestSomething                    0.1.0    -        user     Arduino CI unit test example                                          
$ cat /Users/ianfixes/Development/arduino_ci/SampleProjects/TestSomething/library.properties 
name=TestSomething
version=0.1.0
author= <my info>
maintainer= <my info>
sentence=Arduino CI unit test example
paragraph=A skeleton library demonstrating CI and unit tests
category=Other
url=https://github.com/Arduino-CI/arduino_ci/SampleProjects/TestSomething
architectures=avr,esp8266
includes=do-something.h
$ ./arduino-cli lib deps TestSomething
Error resolving dependencies for TestSomething: looking for library: library TestSomething not found

```

In other words, 

1. the library exists as a symlink in the directory that `arduino-cli` agrees is the proper library directory
2. `arduino-cli` detects the library
3. the library contains a `library.properties`
4. `arduino-cli` can't determine the deps of the library it already "knows" exists

Am I missing something obvious or quirky here?

**Pull request merged**
