### PR TITLE
Prevent name clashes with math macros

### LINKED ISSUE #133: Improve mocks of builtin macros
A post to the arduino developers' mailing list suggests a smarter way to do macros for (e.g.) `max` using "statement expressions":

```c++
#define max(a,b) \
  ({ typeof (a) _a = (a); \
      typeof (b) _b = (b); \
    _a > _b ? _a : _b; })
```

Adopting this will prevent double-evaluating `a` and `b` if for some reason they themselves are expressions with side effects.

### PR DESCRIPTION
**Pull request by jgfoster**
This takes the edits from [here](https://github.com/matthijskooijman/arduino_ci/commit/e356ad78f36720d66ff46551d444f1a3687a484b) and makes them a separate PR.

Fixes #133 (and #165), simplifies #189, and replaces part of #144.

### CODE REVIEW

**Comment by ianfixes** [comment]
I see both a template and a macro definition of `max`.  If both are needed, can you add some code comments explaining that?

**Comment by ianfixes** [comment]
Oh, I see what's happening: `#ifdef __cplusplus` wraps the whole section.  Can you indent the "body" of both the `#ifdef` and the `#else` sections of `__cplusplus` to make them more evident?

**Comment by jgfoster** [comment]
Indent added (note that it would be undone by `clang-format`).

**Comment by ianfixes** [comment]
I know the formatting isn't standard.  There is a lot of c++-side stuff that I'd prefer to keep on the readability side, since this project is still working its way to feature-completeness.  Once it works, I'm hoping the larger group of contributors that have joined in will be able to help me take a second look at how it all could be made more solid.

The end goal would be some direct tie-in with the Arduino project itself to enable these sorts of tests in a batteries-included sort of way in the IDE.  But that's a long way off, if ever.

**Pull request merged**
