### PR TITLE
Added arduino nano every config

### PR DESCRIPTION
**Pull request by midasgossye**
Added platform configuration for the arduino nano every in default.yaml.
Check [this issue](https://github.com/Arduino-CI/action/issues/21) for more details.
## Highlights from `CHANGELOG.md`
* Added ```nano_every``` platform to represent ```arduino:megaavr``` architecture
* See CHANGELOG.md for more

### CODE REVIEW

**Comment by ianfixes** [comment]
Please add a changelog entry like "Added `nano_every` platform to represent the `arduino:megaavr` architecture"

Regarding the test failures, I think the unit tests should be updated to include your platform... If you're not comfortable fixing the unit test yourself, just edit this PR to be against the `tdd` branch and I'll merge that in even when failing.

**Comment by midasgossye** [comment]
My bad for forgetting to add a changelog entry, sorry... 🤦 
Should be added now. I tried to look into changing the unit tests but I'm afraid I will do more harm than good since I'm not familiar with Ruby 😅 
I changed the base branch form master to tdd like you suggested.

**Comment by jgfoster** [comment]
> Regarding the test failures, I think the unit tests should be updated to include your platform.

@ianfixes, I'm looking at open PRs and not sure what you are suggesting. It looks like all tests pass (or passed a year ago!). Are you suggesting adding `nano` to `unittest/platforms` in `SampleProjects/TestSomething/.arduino-ci.yml`? It seems that the existing list is intentionally short and does not include all possible platforms so I'm not sure how the existing list was selected. Thanks!

**Comment by ianfixes** [comment]
Ouch, time has gone by quickly.  

The comment I made was in regard to this line being deleted:

https://github.com/Arduino-CI/arduino_ci/pull/287/commits/07087041b9df8f9282e3545b3bdc6d9a3869f981#diff-92a4a126d74841479f7a742fb740ce8edf0d48218b8d11adf405e92d860dda93L197

I think this PR should not go through unless that line is re-added and the resulting test failures addressed.

**Comment by ianfixes** [comment]
Integrated into #334 and seems to work in that context

**Comment by ianfixes** [comment]
This has merged as part of #334 and was released in [`v1.4.0`](https://github.com/Arduino-CI/arduino_ci/releases/tag/v1.4.0)

**Pull request closed without merging**
