### PR TITLE
Make LED_BUILTIN definition available for Arduino Due, Zero and Circuit Playground

### PR DESCRIPTION
**Pull request by hlovdal**
Updates to CHANGELOG.md will trigger conflicts for this branch (`led_builtin.m`, rebased on top of `master`) when #338 is completed (or if this is done first, then #338 will get conflicts).

There is an alternative branch `led_builtin` applied in series with other branches that does not have those conflicts when #338 is completed. Let me know if you rather want that one merged (later).

### CODE REVIEW

**Comment by ianfixes** [comment]
Can you confirm that the defined value should be `13` for these platforms?  If not, can you open an issue for us to look into that later?

**Comment by hlovdal** [comment]
Ok, I'll check (later).

**Comment by hlovdal** [comment]
Confirmed. Adding

```C++
static_assert(LED_BUILTIN == 13, "not 13");
```

to main.cpp and compiling with

```shell
~/arduino-cli compile --fqbn arduino:avr:circuitplay32u4cat .
~/arduino-cli compile --fqbn adafruit:avr:circuitplay32u4cat .
~/arduino-cli compile --fqbn adafruit:samd:adafruit_circuitplayground_m0 .
~/arduino-cli compile --fqbn arduino:sam:arduino_due_x .
~/arduino-cli compile --fqbn arduino:sam:arduino_due_x_dbg .
```

all succeeds.

(package install steps from [here](https://github.com/adafruit/arduino-board-index/issues/47#issuecomment-592674804))

**Comment by ianfixes** [comment]
Thanks for checking, I really appreciate it!

**Pull request merged**
