### PR TITLE
Support for dtostrf()

### PR DESCRIPTION
**Pull request by jgfoster**
This is a function provided by Arduino that isn't in the standard C library.

### CODE REVIEW

**Comment by jgfoster** [comment]
Sorry, this should have been a branch from master. Let me know if you want it resubmitted.

**Comment by jgfoster** [comment]
This PR was a branch from main instead of master so has been replaced with #309.

**Comment by ianfixes** [comment]
Which is the replacement PR?  309 is _this_ issue

**Comment by jgfoster** [comment]
Yes, that's right. My `main` has all my changes merged into it and I should be making my PRs on a branch from `master` which tracks upstream master. I made the mistake of branching from my `main` so the initial PR had a huge number of modified files. In order to do a clean merge I recreated the proposed changes in a clean PR.

**Comment by jgfoster** [comment]
And, if you have any substantive comments on closed PRs (like this one), I'm happy to revert or supplement...

**Comment by ianfixes** [comment]
Any changes that have unit tests attached are generally fine with me, we can always add to the suite if/when we find a problem with the implementation.

**Pull request closed without merging**
