### PR TITLE
Further bugfixes and documentation fixes

### LINKED ISSUE #159: Distinguish between unit test compilation and "normal" compilation
## Feature Request

via https://github.com/ianfixes/arduino_ci/issues/150#issuecomment-689887131 

> I find that I'd like a way to distinguish between when code is compiled from the Arduino IDE and when code is compiled from arduino_ci. Ideal would be something like `#define ARDUINO_CI` but the closest I've come is `MOCK_PINS_COUNT`

## Initial thoughts

There is some ability to do this already, as a per-project workaround, by copying platform definitions from `default.yml` and [adding to the `defines` section of a platform](https://github.com/ianfixes/arduino_ci/blob/master/REFERENCE.md#defining-new-arduino-platforms):

```yaml
# copied from default.yml in september 2020
platforms:
  uno:
    board: arduino:avr:uno
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega328P__

        # This is the workaround described above
        - ARDUINO_CI
      warnings:
      flags:
```

Since the platform definitions' `gcc` section applies only to unit testing (i.e. it's not AVR compilation), this is safe.  But possibly not ideal.

## Discussion points

What are best practices for injecting "evidence" of test platforms into compilation?  For example, should we copy [the pattern used by the `ARDUINO` constant](https://stackoverflow.com/q/30927908/2063546), and if so, what would the numbers represent?

### LINKED ISSUE #272: Configuration files in examples/ are not considered
via https://github.com/Arduino-CI/action/issues/17#issuecomment-761957674

> not allowing a configuration file in the ~/examples/ directory, but allowing a file in the ~/tests/directory is inconsistent

This is a fair point. The question is whether to apply platform/package installation rules upon entering `examples/` or simply rely on the overridden config at the individual examples level to accomplish it.  My initial thought is to ignore the contents of `examples/.arduino-ci.yml` by itself and focus solely on the subdirectories which may or may not override that.

### LINKED ISSUE #273: add logging lines to the test runner that indicate config overrides (or lack of)
Each of the places in CI where a config file is overridden (or has the opportunity to be overridden), the CI runner script should indicate this to the user.

It should be something like the following cases:

```
overriding configuration...                                             <none>
overriding configuration...                               test/.arduino-ci.yml
overriding configuration...                          examples/.arduino-ci.yaml
overriding configuration...                 examples/FooSketch/.arduino-ci.yml
```

### LINKED ISSUE #336: Running "bundle install --path vendor/bundle" generates deprecated warning
## System

- OS:  Linux, Fedora 37
- `ruby -v`: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
- `bundle -v`: Bundler version 2.3.26
- `bundle info arduino_ci`: link to git clone `(checked` out `2021-02-15_rescue` branch).

## Issue Summary

The readme file contains the following suggested command

```shell
$ bundle install --path vendor/bundle   # adds packages to local library
```

However running it generates a deprecated warning:

```text
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag
Resolving dependencies...Fetching gem metadata from https://rubygems.org/....
...
Using bundler 2.3.26
Fetching os 1.1.4
Fetching rubyzip 1.3.0
Installing os 1.1.4
Installing rubyzip 1.3.0
Using arduino_ci 1.3.0 from source at `../arduino_ci` and installing its executables
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```

### LINKED ISSUE #339: ESP32 failing to install in CI build
## Issue Summary

via email from @RobTillaart:

Errors in [this](https://github.com/RobTillaart/FRAM_I2C/actions/runs/3794469015/jobs/6452582233#step:4:327) or [that](https://github.com/RobTillaart/FRAM_I2C/actions/runs/3794464230/jobs/6452572975#step:4:326)  FRAM_I2C build:

> Error initializing instance: Loading index file: loading json index file /home/runner/.arduino15/package_esp32_index.json: open /home/runner/.arduino15/package_esp32_index.json: no such file or directory

## Arduino or Unit Test Code, Illustrating the Problem
https://github.com/RobTillaart/FRAM_I2C/commit/d2a06226f09569258ed166bf98519c287b23a270

### PR DESCRIPTION
**Pull request by ianfixes**
This cleans up the `v1.4.0` release and makes progress on past milestones

* Fixes #159
* Fixes #339
* Fixes #336 
* Fixes #273
* Fixes #272

### CODE REVIEW

**Comment by ianfixes** [comment]
I will need to address https://github.com/Arduino-CI/arduino_ci/issues/339 in this PR.

**Comment by hlovdal** [comment]
#339 should be fixed by my [`2021-02-15_rescue.updates` branch](https://github.com/hlovdal/arduino_ci/commits/2021-02-15_rescue.updates). It is now rebased on top of `ianfixes/2022-12-28_tweaks`.

**Comment by ianfixes** [comment]
@hlovdal disregard my other message on your closed PR, I will cherry pick your changes into this branch

**Comment by ianfixes** [comment]
I believe this verifies the fix for #339 -- fixing the problem that @RobTillaart was seeing:
https://github.com/ianfixes/FRAM_I2C/actions/runs/3876505881/jobs/6610424853

**Comment by RobTillaart** [comment]
The PR looks good to me so if there are no other showstoppers please merge and add a tag!
👍

**Comment by ianfixes** [comment]
Sorry for the delay, this has been released as `v1.5.0`

**Pull request merged**
