### PR TITLE
Fix problem with warnings for platforms

### PR DESCRIPTION
**Pull request by jgfoster**
As a follow-up to #292, I tried to add warnings for a platform and found that it doesn't work. This should fix it.

### CODE REVIEW

**Comment by ianfixes** [comment]
Is the YAML file a necessary part of the fix?  If not, I'll just fix the typo in my branch

**Comment by jgfoster** [comment]
The YAML file is a _test_ of the fix. If you add the YAML file without the `cpp_library.rb` then you can see the failure.

**Comment by ianfixes** [comment]
Understood.  I'm going to exercise this with unit testing instead, as I should have done earlier to prevent such an obvious error.

**Comment by ianfixes** [comment]
https://github.com/Arduino-CI/arduino_ci/pull/296/commits/375c3f3ea7e5215560c2cbcb66d3358821374666

**Pull request merged**
