### PR TITLE
Big fix branch for 2021

### LINKED ISSUE #269: Allow test runner script to increase the default width, with a minimum
## Feature Request

The `arduino_ci.rb` test runner script hard-codes `WIDTH = 80` as a target text formatting for all its checkmarks, x's, and informational outputs.  

80 should definitely be the minimum, but we should explore options for letting the user decide on a larger width as per their preferences.  It's unclear whether we should attempt something like `tput cols` (which won't work on Windows) or leave that to the user to simply collect that value on their own and apply it.

An environment variable is probably the easiest and most appropriate way to accomplish this.

### LINKED ISSUE #282: Poor error reporting for undefined platforms
via https://github.com/Arduino-CI/action/issues/21

Consider this compilation config

```yaml
compile:
  platforms:
    - this_doesnt_exist
```

This produces `NoMethodError: undefined method `[]' for nil:NilClass error` instead of a sensible message about the platform not being defined.  This is a regression in the error communication to the user.

### LINKED ISSUE #283: Line ending inconsistencies in cpp/arduino/avr/ files
On a fresh checkout on a new machine I get 266 files shown as modified. Further investigation shows that io+.h files have `\r` in them. I note that `.gitattributes` has `* text eol=lf` in it with a comment suggesting that this should make things consistent, but it doesn't.

Perhaps these files got copied/generated initially in a Windows format and were never fixed? In any case, following the instructions [here](https://stackoverflow.com/questions/9976986/force-lf-eol-in-git-repo-and-working-copy/42135910#42135910) seems to have fixed it. I'm not enough of an expert in Git line endings to know if this is the right solution, but I'll offer a PR for discussion.

### LINKED ISSUE #288: Reporting compile errors in GitHub Actions
I have some code that compiles and runs on my workstation but not in GitHub. In order to verify the output problem, I created a simple failing test with `foo;` as the only command in a function. Following is my local output with a nice, useful description of the error:

```
undle exec arduino_ci.rb --testfile-select filesystem.cpp
                           .                  __  ___
                   _, ,_  _| , . * ._   _    /  `  | 
                  (_| [ `(_] (_| | [ ) (_)   \__. _|_   v1.3.0

Host OS...                                                                   osx
Located arduino-cli binary...                         /Users/jfoster/arduino-cli
Found libraries directory...          /Users/jfoster/Documents/Arduino/libraries
Environment variable CUSTOM_INIT_SCRIPT...                                    ''
Environment variable USE_SUBDIR...                                            ''
Installing library under test...                                               ✓
Library installed at... /Users/jfoster/Documents/Arduino/libraries/TestSomething

================================================================================
Beginning the next phase of testing...                              Unit testing
The set of compilers (1) isn't empty...                                        ✓
Checking g++ version... 
    Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
    Apple clang version 12.0.0 (clang-1200.0.32.29)
    Target: x86_64-apple-darwin19.6.0
    Thread model: posix
    InstalledDir: /Library/Developer/CommandLineTools/usr/bin
...Checking g++ version                                                        ✓
libasan availability for g++...                                             true
Library conforms to Arduino library specification...                         1.5
Requested unittest platform 'uno' is defined in 'platforms' YML...             ✓
Configured platforms that match architectures in library.properties... 
    uno
...Configured platforms that match architectures in library.properties          

Unit testing filesystem.cpp with g++ for uno... 

Last command:  $ g++ -std=c++0x -o /Users/jfoster/Documents/Arduino/arduino_ci/SampleProjects/TestSomething/unittest_filesystem.cpp.bin -DARDUINO=100 -g -O1 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -D__AVR__ -D__AVR_ATmega328P__ -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -I/Users/jfoster/Documents/Arduino/arduino_ci/cpp/arduino -I/Users/jfoster/Documents/Arduino/arduino_ci/cpp/unittest -I/Users/jfoster/Documents/Arduino/libraries/TestSomething/src /Users/jfoster/Documents/Arduino/arduino_ci/cpp/arduino/Arduino.cpp /Users/jfoster/Documents/Arduino/arduino_ci/cpp/arduino/Godmode.cpp /Users/jfoster/Documents/Arduino/arduino_ci/cpp/arduino/stdlib.cpp /Users/jfoster/Documents/Arduino/arduino_ci/cpp/unittest/ArduinoUnitTests.cpp /Users/jfoster/Documents/Arduino/libraries/TestSomething/src/test-something.cpp /Users/jfoster/Documents/Arduino/libraries/TestSomething/test/filesystem.cpp

/Users/jfoster/Documents/Arduino/libraries/TestSomething/test/filesystem.cpp:9:3: error: use of undeclared identifier 'foo'; did you mean 'for'?
  foo;
  ^~~
  for
/Users/jfoster/Documents/Arduino/libraries/TestSomething/test/filesystem.cpp:9:6: error: expected '(' after 'for'
  foo;
     ^
2 errors generated.
...Unit testing filesystem.cpp with g++ for uno                                ✗
```

Following is the output in the [GitHub Action](https://github.com/jgfoster/arduino_ci/runs/1912006292?check_suite_focus=true):

```
    file filesystem.cpp (using g++)
Last command: 
========== Stdout:

========== Stderr:

      filesystem.cpp builds successfully (FAILED - 1)
      filesystem.cpp passes tests (PENDING: Can't run the test program because it failed to build)
```

This is distinctly unhelpful!

### LINKED ISSUE #295: NoMethodError: undefined method `map' for nil:NilClass
Running `Arduino-CI/action@stable-1.x` result in `NoMethodError` :

I use the default workflow :
```
name: Arduino_CI

on: [pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Arduino-CI/action@stable-1.x
```
And my project is ok for [`arduino-lint` action](https://github.com/marketplace/actions/arduino-arduino-lint-action) :
```
CI-test/
├── CI-test.ino
├── examples
│   └── example.c
├── README.md
└── test
    └── test.c
```
But I have always this issue :
```
================================================================================
Beginning the next phase of testing...           Compilation of example sketches
bundler: failed to load command: /action/bundle/ruby/2.6.0/bin/arduino_ci.rb (/action/bundle/ruby/2.6.0/bin/arduino_ci.rb)
NoMethodError: undefined method `map' for nil:NilClass
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/lib/arduino_ci/cpp_library.rb:135:in `example_sketches'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:450:in `perform_example_compilation_tests'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.3.0/exe/arduino_ci.rb:536:in `<top (required)>'
  /action/bundle/ruby/2.6.0/bin/arduino_ci.rb:23:in `load'
  /action/bundle/ruby/2.6.0/bin/arduino_ci.rb:23:in `<top (required)>'
```

### PR DESCRIPTION
**Pull request by ianfixes**
There are a lot of interrelated things to fix, so this branch intends to be a heavy-handed attempt to combine all those fixes.

## Highlights from `CHANGELOG.md`

* See CHANGELOG.md for more

## Issues Fixed

* Fixes #295
* Fixes #283
* Supersedes #285 
* Fixes #282
* Supersedes #297
* Fixes #288
* Supersedes #289
* Supersedes #298 
* Supersedes #286 
* Fixes #269
* Supersedes #290
* Addresses #280

### CODE REVIEW

**Comment by hlovdal** [comment]
I have two fixes you can cherry-pick from the branch [2021-02-15_beta.update](https://github.com/hlovdal/arduino_ci/tree/2021-02-15_beta.update). The first one is trivial, but the second one about the `--path` argument I am not sure if is correct, so maybe just use that as a reference to investigate what the correct commands should be. 

With the `crlf` branch merged into `master`, you can drop the commit "Update CHANGELOG.md to describe line endings change." from this branch.

**Comment by ianfixes** [comment]
@hlovdal It doesn't look like there's too much to bring over https://github.com/ianfixes/arduino_ci/compare/2021-02-15_beta...hlovdal:2021-02-15_beta.update

**Comment by ianfixes** [comment]
@jgfoster I'll try to break this up into smaller pieces so we can get it merged in, but I'm not sure which of the issues fixed (see PR description) are most pressing

**Comment by jgfoster** [comment]
@ianfixes, That's fine. As you have seen, I've merged most of my changes. The one remaining is the one to build a library once and use it for the remaining tests. While this has had an enormous speed improvement in our application, I'm not seeing the same improvement in the TestSomething case. For that reason I'm holding back and on merging it till I can better document the improvement.

As to the other PRs, I do intend to review them and merge them as I understand what is happening (I've given my own preferential treatment since I understand them!).

**Comment by ianfixes** [comment]
Pulled into #334 with the exception of https://github.com/Arduino-CI/arduino_ci/commit/1ee342c18740e665b265cc81af346c9ee160c208

**Comment by ianfixes** [comment]
This has merged as part of #334 and was released in [`v1.4.0`](https://github.com/Arduino-CI/arduino_ci/releases/tag/v1.4.0).  https://github.com/Arduino-CI/arduino_ci/commit/1ee342c18740e665b265cc81af346c9ee160c208 is being tracked in #337

**Pull request closed without merging**
